### ISSUE TITLE
RtAudio: no compiled support for specified API argument!

### ISSUE THREAD

**Issue by Zipdox** [almoghamdani/audify#12]
When I try to run this
```js
const rtAudio = new RtAudio(4);
```
I get this
```
RtAudio: no compiled support for specified API argument!
```
How to I build audify with JACK support?

**Comment by Zipdox** [comment]
Ok it took me some time to figure it out due to lack of documentation. Just had to clone the repo manually and `npm install` and `npm run build-binaries` and then from my own project `npm i ./audify/`.

**Comment by Zipdox** [comment]
After cloning the repo and rerunning the commands that fixed the issue last time, it appears that it's compiling with JACK support.

**Comment by elgiano** [comment]
I had the same problem, it looks like it works for me only if I recompile audify after having installed it in my project. Can anyone explain me why? Here are my (working) steps:

```bash
git clone --recursive https://github.com/almoghamdani/audify
cd audify
npm install
cd ..
npm install ./audify
cd audify
npx cmake-js rebuild
cd ..
```
I've tried running `npx cmake-js rebuild` before `npm install ./audify` and it didn't work, still giving me the error @Zipdox got, while with the sequence of commands above it works perfectly.

:thinking:

**Comment by Zipdox** [comment]
It would be best if the shipped binaries are compiled with all API support.

**Comment by almoghamdani** [comment]
Unfortunately, I cannot add support for JACK in the prebuilt-binaries because RtAudio implicitly links with it.
Therefore, any system that doesn't have JACK installed will fail to import Audify :disappointed:
