### ISSUE TITLE
JACK client connects but no data

### ISSUE THREAD

**Issue by Zipdox** [almoghamdani/audify#13]
This is my code:
```js
const { RtAudio, RtAudioFormat, RtAudioApi } = require("audify");
const fs = require('fs');

const rtAudio = new RtAudio(RtAudioApi.UNIX_JACK);

const writer = fs.createWriteStream('out.pcm');

rtAudio.openStream(
    null,
    { deviceId: rtAudio.getDefaultOutputDevice(),
        nChannels: 2,
        firstChannel: 0
    },
    RtAudioFormat.RTAUDIO_SINT16,
    48000,
    128*3, // JACK set to 128 Frames/Period and 3 Periods/Buffer
    "test",
    (inputData) => {
        console.log(inputData);
        writer.write(inputData);
    }
);

rtAudio.start();
```

When I run it, the JACK client connects, but there's no data coming through. After some time the client disconnects but the script keeps running.

If I replace UNIX_JACK with LINUX_PULSE it does receive data and the PCM file can be imported and played by Audacity. However, the PulseAudio client also disconnects after a short while and the script keeps running, obviously not receiving anymore data.

**Comment by philhartung** [comment]
You should probably use `rtAudio.getDefaultInputDevice()` instead of `rtAudio.getDefaultOutputDevice()`. The rest of the code looks fine to me.

**Comment by Zipdox** [comment]
Tried, still nothing.

**Comment by philhartung** [comment]
I would first verify that `rtAudio.getDefaultInputDevice()` is actually the soundcard you want to access:
```javascript
const { RtAudio, RtAudioApi } = require('audify');
const rtAudio = new RtAudio(RtAudioApi.UNIX_JACK);
let devices = rtAudio.getDevices();
console.log(devices[rtAudio.getDefaultInputDevice()]);
```
The output should contain the name of the soundcard.

You should also terminate Pulse, as Pulse might be accessing the soundcard and blocking JACK from accessing the device. If that doesn't work I would try a with a different soundcard or on a different computer.

**Comment by Zipdox** [comment]
I don't think you understand how JACK works. JACK is a graph-based audio routing system. JACK works with so called "clients". Both sound devices and programs are clients.

Like I said, the client connects just fine. Pulse isn't using my sound card because JACK is already using it. Pulse works because I'm using pulseaudio-module-jack.

So the issue isn't with picking the device
![jack works fine](https://user-images.githubusercontent.com/42157341/115154014-104e8380-a079-11eb-932b-47bb98976364.png)

**Comment by Zipdox** [comment]
Ok for some reason now it suddenly works but it segfaults after some time.
