### ISSUE TITLE
Audio interface disconnected detection and bugs

### ISSUE THREAD

**Issue by NatsumiFox** [almoghamdani/audify#14]
I am having an issue with Audify on Windows 10. When an audio device is disconnected (for example disabling it via sound device settings), various things might happen. on WASAPI, the entire program just crashes immediately, on DirectSound, the audio stops working and will never start working again, and ASIO just flat out doesn't work in the first place. After talking with friends who have used other programs that use rtAudio, this is also an issue in those programs as well, however they claimed the [`errorCallback`](https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L324) on openStream could be used to handle these kind of situations? Though it looks like this is a [known issue already](https://github.com/thestk/rtaudio/issues/268). Audify doesn't seem to support the errorCallback method or any way of detecting dropped audio/catching errors that might crash the entire application. This is very bad, because in my application, users may lose hours worth of progress on their project simply because the program crashes seemingly out of nowhere. For reference, [this is how I use rtAudio at the moment](https://github.com/ZorroTrackerDev/ZorroTracker/blob/main/src/system/audio.ts#L150).

Any input on potential fixes/workarounds/other solutions? Preferably I'd be able to detect when the device is disconnected so I can re-create it with rtAudio, but being able to not crash at the very least would really be preferred.

**Comment by almoghamdani** [comment]
This is mainly an RtAudio issue, but I tried to mitigate this issue by adding a default internal callback for `errorCallback` (when set on WASAPI, the application doesn't crash anymore).
Also, I added support for a user-defined `errorCallback` (a new optional parameter for `openStream`). Using this parameter you can detect audio interface disconnection and re-create the stream using a different interface, which hopefully helps you :)
These changes were added in [1.6.0](https://github.com/almoghamdani/audify/releases/tag/v1.6.0)
