### ISSUE TITLE
using audify with the web audio api via electron

### ISSUE THREAD

**Issue by marcelblum** [almoghamdani/audify#17]
Audify includes AFAICT the only currently maintained and fully working Node implementation of RtAudio, giving it quite a bit of utility for routing audio - awesome! I am looking for a way to pipe audio rendered in realtime by the Web Audio api into an instance of Audify's RtAudio in an Electron app. My goal is to be able to output audio generated by the browser (e.g. Electron's renderer process) to an ASIO-only device on Windows. Does anyone have any idea on approaches for this? I was thinking perhaps through a WebRTC `MediaStream` (`AudioContext.createMediaStreamDestination()`) but I am not sure if this is the optimal route. Any ideas/pointers/nudges in the right direction would be appreciated!

**Comment by marcelblum** [comment]
In case anyone comes across this just wanted to post the solution I settled on, the best way to get Web Audio raw output buffers in realtime seems to be via an `audioWorklet`, which is actually a pretty simple method and no need to mess with WebRTC streams at all. So I have the worklet itself instantiate RtAudio from audify and pipe the raw input PCM data directly to `rtAudio.write()` (in Electron worklets can call Node.js modules as long as `nodeIntegrationInWorker` is `true`). I connect it to a Web Audio node back in the main thread (in my case I connect my main master output node to the worklet), and the audio is routed to the RtAudio stream nicely, tested up to 32-bit 96kHz output, no glitching. Only issues I came across is that some ASIO devices I tested did not seem to work with in RtAudio. I may open a separate issue about that to investigate further if I can't figure it out.

If anyone's more curious I can post some sample code. Or if anyone has any feedback/ideas for better implementation I'm open to hearing.

**Comment by Durgaprasad-Budhwani** [comment]
HI, @marcelblum Thank you very much for the code snippet. Much Appreciated. I will reach out to you again if I am stuck at any place.
