### ISSUE TITLE
Can't use devices that have a different channel count for input vs output.

### ISSUE THREAD

**Issue by daankets** [almoghamdani/audify#19]
Whenever I try to use Audify for opening a channel on a device (like my macbook pro) where the channel count for the microphone doesn't match the channel count for the output, the library throws an exception:

```
Error: RtApiCore::probeDeviceOpen: the device (1) does not support the requested channel count.
```

Am I correct to assume that this is an RtAudio bug?

**Comment by almoghamdani** [comment]
Correct, this an [RtAudio](https://github.com/thestk/rtaudio) bug.
