### ISSUE TITLE
rtAudio.openStream device id missing.

### ISSUE THREAD

**Issue by nicnacnic** [almoghamdani/audify#21]
Hi,
I've recently come across an issue with the rtAudio object. Even though I'm passing a device ID to the object, it still gives me an error.
```
let device= 0;
rtAudio.openStream(
            {
                deviceId: device,
                nChannels: 1
            },
            RtAudioFormat.RTAUDIO_SINT16,
            48000,
            1920,
            "Output",
            mixer => rtAudio.write(mixer)
        );
```
Error: ` The 'device id' stream parameter is missing or invalid!`
I've also tried with `rtAudio.getDefaultOutputDevice()`, and I still get the same issue. Any ideas?

**Comment by marcelblum** [comment]
Your code is missing the `inputParameters` argument. If you just want to open an output-only stream it can be `undefined`. But you're also including an `inputCallback` so maybe you do want an combined input/output stream? For output-only this would work:
```
rtAudio.openStream(
            {
                deviceId: device,
                nChannels: 1
            },
            undefined,
            RtAudioFormat.RTAUDIO_SINT16,
            48000,
            1920,
            "Output"
        );
```

**Comment by nicnacnic** [comment]
Thanks @marcelblum, indeed that was the issue. The weird thing is that I've used the same code before and I didn't have any issues. But yeah even if you don't use the input you have to set it to undefined.
