### ISSUE TITLE
request to bump rtaudio version

### ISSUE THREAD

**Issue by marcelblum** [almoghamdani/audify#50]
The current (>1 year old) version of rtaudio used here has a few fatal bugs (since fixed) which trickle down into audify, including this ASIO crashing bug https://github.com/thestk/rtaudio/pull/393

**Comment by almoghamdani** [comment]
Done in v1.9.0 :)

**Comment by marcelblum** [comment]
Thank you. Sorry but I didn't know how to submit a PR  to update a submodule. I had compiled my own fork a few months back pulling in the latest rtaudio and confirmed the ASIO bug was fixed. Will test your new update soon.
