### ISSUE TITLE
Support Arm

### ISSUE THREAD

**Issue by PiecePaperCode** [almoghamdani/audify#9]
Trying to use your Lib on a Raspberry Pi 4 fails. Your bins are all x64. Could you offer advice to compile for ARM?.

**Comment by almoghamdani** [comment]
Hi, I will take a look into compiling prebuilds for arm64.

**Comment by PiecePaperCode** [comment]
https://github.com/philhartung/aes67-monitor/issues/3

it looks like the previous version compiled without problems and it just recently stopped working. as there was no distribution it would just compile it itself in arm just fine with npm. Downgreading the lib is the workaround solution.
